version: '3.8'

services:
  modmeister:
    image: ghcr.io/laszlokonyari/modmeister:latest
    container_name: modmeister-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./botdatabase.db:/app/botdatabase.db

  watchtower:
    image: containrrr/watchtower
    container_name: modmeister-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup modmeister-bot